name: Render Quarto

on:
  push:
    branches: [main]

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Restore renv
        run: |
          Rscript -e 'install.packages("renv")'
          Rscript -e 'renv::restore()'

      - name: Render Quarto
        run: quarto render